#!/usr/bin/env python3
import googletrans
import fileinput


def delete_non_string(text):
    return True if(len(text.strip()) > 0) else False


def text_edit(text):
    replace_list = (("\n", " "), ("  ", " "))
    for before, after in replace_list:
        text = text.replace(before, after)

    text = text.split(".")
    text = list(filter(delete_non_string, text))
    return ".".join(text)


def main():
    translator = googletrans.Translator()
    text = " ".join(list(fileinput.input()))
    text = text_edit(text)
    trans_text = translator.translate(text, src="en", dest="ja")
    print(trans_text.text)


main()
