#!/usr/bin/env python3
import googletrans
import fileinput
import argparse


def arg_parse():
    parser = argparse.ArgumentParser(description="fileinput & argparse")
    parser.add_argument('files', metavar='FILE', nargs='*',
                        help='files to read, if empty, stdin is used')
    parser.add_argument('-bt', '--btrans', type=str,
                        help='Language before change')
    parser.add_argument('-at', '--atrans', type=str,
                        help='Language after change')

    return parser.parse_args()


def delete_non_string(text):
    return True if(len(text.strip()) > 0) else False


def text_edit(text):
    replace_list = (("\n", " "), ("  ", " "))
    for before, after in replace_list:
        text = text.replace(before, after)

    text = text.split(".")
    text = list(filter(delete_non_string, text))
    return ".".join(text)


def main():
    parse = arg_parse()
    translator = googletrans.Translator()
    text = " ".join(list(fileinput.input(files=parse.files)))
    text = text_edit(text)
    trans_text = translator.translate(
        text, src=parse.btrans, dest=parse.atrans)
    print(trans_text.text)


main()
