#!/usr/bin/env python3
import os
import deepl
import googletrans
import fileinput
import argparse


def arg_parse():
    parser = argparse.ArgumentParser(description="fileinput & argparse")
    parser.add_argument('files', metavar='FILE', nargs='*',
                        help='files to read, if empty, stdin is used')
    parser.add_argument('-bt', '--btrans', type=str,
                        help='Language before change')
    parser.add_argument('-at', '--atrans', type=str,
                        help='Language after change')

    return parser.parse_args()


def delete_non_string(text):
    return True if(len(text.strip()) > 0) else False


def text_edit(text):
    replace_list = (("\n", " "), ("  ", " "))
    for before, after in replace_list:
        text = text.replace(before, after)

    text = text.split(".")
    text = list(filter(delete_non_string, text))
    return ".".join(text)


def main():
    parse = arg_parse()
    directory = os.path.dirname(__file__)
    f = open(directory + "/.auth_key", "r")
    deepl_api_key = f.read()
    translator = deepl.Translator(deepl_api_key)

    text = " ".join(list(fileinput.input(files=parse.files)))
    text = text_edit(text)

    # translator = googletrans.Translator()
    # trans_text = translator.translate(
    #     text, src=parse.btrans, dest=parse.atrans)
    result = translator.translate_text(text, target_lang=parse.atrans)
    print(result.text)


main()
